/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import {HTMLStencilElement, JSXBase} from '@stencil/core/internal';
export namespace Components {
  interface ECollecting {
    owllyId: string;
  }
}
declare global {
  interface HTMLECollectingElement extends Components.ECollecting, HTMLStencilElement {}
  var HTMLECollectingElement: {
    prototype: HTMLECollectingElement;
    new (): HTMLECollectingElement;
  };
  interface HTMLElementTagNameMap {
    'e-collecting': HTMLECollectingElement;
  }
}
declare namespace LocalJSX {
  interface ECollecting {
    owllyId?: string;
  }
  interface IntrinsicElements {
    'e-collecting': ECollecting;
  }
}
export {LocalJSX as JSX};
declare module '@stencil/core' {
  export namespace JSX {
    interface IntrinsicElements {
      'e-collecting': LocalJSX.ECollecting & JSXBase.HTMLAttributes<HTMLECollectingElement>;
    }
  }
}
