/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface OwllyCollect {
        /**
          * The browser lang is used per default. Use this option to overwrite the automatic detection and use the language you would like to use.
         */
        "customLang": 'de' | 'fr' | 'it' | 'en';
        /**
          * Style the button with a dark or light theme?
         */
        "mode": 'dark' | 'light';
        /**
          * IntersectionObserver rootMargin property.
         */
        "observerRootMargin": string;
        /**
          * IntersectionObserver threshold property.
         */
        "observerThreshold": number | number[];
        /**
          * The ID to be provided to Owlly in order to load the initiative and other content for navigation.
         */
        "owllyId": string;
    }
}
declare global {
    interface HTMLOwllyCollectElement extends Components.OwllyCollect, HTMLStencilElement {
    }
    var HTMLOwllyCollectElement: {
        prototype: HTMLOwllyCollectElement;
        new (): HTMLOwllyCollectElement;
    };
    interface HTMLElementTagNameMap {
        "owlly-collect": HTMLOwllyCollectElement;
    }
}
declare namespace LocalJSX {
    interface OwllyCollect {
        /**
          * The browser lang is used per default. Use this option to overwrite the automatic detection and use the language you would like to use.
         */
        "customLang"?: 'de' | 'fr' | 'it' | 'en';
        /**
          * Style the button with a dark or light theme?
         */
        "mode"?: 'dark' | 'light';
        /**
          * IntersectionObserver rootMargin property.
         */
        "observerRootMargin"?: string;
        /**
          * IntersectionObserver threshold property.
         */
        "observerThreshold"?: number | number[];
        /**
          * The ID to be provided to Owlly in order to load the initiative and other content for navigation.
         */
        "owllyId"?: string;
    }
    interface IntrinsicElements {
        "owlly-collect": OwllyCollect;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "owlly-collect": LocalJSX.OwllyCollect & JSXBase.HTMLAttributes<HTMLOwllyCollectElement>;
        }
    }
}
